name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'lisesoee2/texttransformer:$(Build.BuildId)'  

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) 


# # Docker
# # Build a Docker image
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - master

# resources:
# - repo: self

# # pool:
# #   vmImage: 'windows-latest'

# variables:
#   tag: '$(Build.BuildId)'

# stages:
# - stage: BuildAndPush
#   displayName: Build image
#   jobs:  
#   - job: DockerImage
#     displayName: Build and push Docker image
#     steps:
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: 'lisesrepo'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'
#         buildContext: '$(Build.SourcesDirectory)/'
#         tags: |
#           $(tag)


# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     # pool:
#     #   vmImage: ubuntu-latest
#     pool:
#       vmImage: 'windows-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/TextTransformer/Dockerfile'
#         buildContext: '$(Build.SourcesDirectory)/TextTransformer/'
#         tags: |
#           $(tag)
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: 'lisesrepo'
#         command: 'push'
