# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'windows-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'lisesrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     # pool:
#     #   vmImage: ubuntu-latest
#     pool:
#       vmImage: 'windows-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/TextTransformer/Dockerfile'
#         tags: |
#           $(tag)
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Docker Hub'
#         repository: 'lisesrepo'
#         command: 'push'
